%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: Z:\_SHARED_FOLDERS\Air Quality\Phase 1\Pathflow of Phase
%    I_DG\RAW DATA\MoEW Data\2015 data\wetransfer-43afdf\DM data  1st Quar.
%    2015.xlsx Worksheet: Deira
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/12/20 19:14:48

%% Import the data, extracting spreadsheet dates in MATLAB serial date number format (datenum)
[~, ~, raw0_0] = xlsread('Z:\_SHARED_FOLDERS\Air Quality\Phase 1\Pathflow of Phase I_DG\RAW DATA\MoEW Data\2015 data\wetransfer-43afdf\DM data  1st Quar. 2015.xlsx','Deira','A10:C8769');%,'',@convertSpreadsheetDates);
[~, ~, raw0_1] = xlsread('Z:\_SHARED_FOLDERS\Air Quality\Phase 1\Pathflow of Phase I_DG\RAW DATA\MoEW Data\2015 data\wetransfer-43afdf\DM data  1st Quar. 2015.xlsx','Deira','F10:F8769');%,'',@convertSpreadsheetDates);
[~, ~, raw0_2] = xlsread('Z:\_SHARED_FOLDERS\Air Quality\Phase 1\Pathflow of Phase I_DG\RAW DATA\MoEW Data\2015 data\wetransfer-43afdf\DM data  1st Quar. 2015.xlsx','Deira','I10:I8769');%,'',@convertSpreadsheetDates);
[~, ~, raw0_3] = xlsread('Z:\_SHARED_FOLDERS\Air Quality\Phase 1\Pathflow of Phase I_DG\RAW DATA\MoEW Data\2015 data\wetransfer-43afdf\DM data  1st Quar. 2015.xlsx','Deira','O10:O8769');%,'',@convertSpreadsheetDates);
[~, ~, raw0_4] = xlsread('Z:\_SHARED_FOLDERS\Air Quality\Phase 1\Pathflow of Phase I_DG\RAW DATA\MoEW Data\2015 data\wetransfer-43afdf\DM data  1st Quar. 2015.xlsx','Deira','U10:U8769');%,'',@convertSpreadsheetDates);
[~, ~, raw0_5] = xlsread('Z:\_SHARED_FOLDERS\Air Quality\Phase 1\Pathflow of Phase I_DG\RAW DATA\MoEW Data\2015 data\wetransfer-43afdf\DM data  1st Quar. 2015.xlsx','Deira','X10:X8769');%,'',@convertSpreadsheetDates);
[~, ~, raw0_6] = xlsread('Z:\_SHARED_FOLDERS\Air Quality\Phase 1\Pathflow of Phase I_DG\RAW DATA\MoEW Data\2015 data\wetransfer-43afdf\DM data  1st Quar. 2015.xlsx','Deira','AA10:AP8769');%,'',@convertSpreadsheetDates);
raw = [raw0_0,raw0_1,raw0_2,raw0_3,raw0_4,raw0_5,raw0_6];
%dateNums = [dateNums0_0,dateNums0_1,dateNums0_2,dateNums0_3,dateNums0_4,dateNums0_5,dateNums0_6];
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace date strings by MATLAB serial date numbers (datenum)
%R = ~cellfun(@isequalwithequalnans,dateNums,raw) & cellfun('isclass',raw,'char'); % Find spreadsheet dates
%raw(R) = dateNums(R);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create dataset array
Diera = dataset;

%% Allocate imported array to column variable names
Diera.columnA = data(:,1);
Diera.DateTime = raw(:,2);
Diera.SO2 = data(:,3);
Diera.NO2 = data(:,4);
Diera.O3 = data(:,5);
Diera.CO = data(:,6);
Diera.PM10 = data(:,7);
Diera.PM25 = data(:,8);
Diera.LowerAmbientTemperature = data(:,9);
Diera.UpperAmbientTemperature = data(:,10);
Diera.BarometricPressure = data(:,11);
Diera.RelativeHumidity = data(:,12);
Diera.WindDirection = data(:,13);
Diera.WindSpeed = data(:,14);
Diera.H2S = data(:,15);
Diera.Toluene = data(:,16);
Diera.OXylene = data(:,17);
Diera.EthylBenzene = data(:,18);
Diera.mpxylene = data(:,19);
Diera.Benzene = data(:,20);
Diera.CH2 = data(:,21);
Diera.NMHC = data(:,22);
Diera.THC = data(:,23);
Diera.Noise = data(:,24);

%% Clear temporary variables
clearvars data raw dateNums raw0_0 dateNums0_0 raw0_1 dateNums0_1 raw0_2 dateNums0_2 raw0_3 dateNums0_3 raw0_4 dateNums0_4 raw0_5 dateNums0_5 raw0_6 dateNums0_6 R;